[toolchain]
channel = "stable"
components = ["default"]
targets = [
    "x86_64-unknown-linux-gnu",
    # "i686-pc-windows-msvc",
    # "x86_64-pc-windows-msvc",
    # "aarch64-pc-windows-msvc",
]
profile = "minimal"
